apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - job.yaml
  - network-policies.yaml
images:
  - name: utcp-t3-media-prover
    newName: utcp-local-registry:5000/utcp/t3-media-prover
    newTag: 0.1.0-k1-dev
