apiVersion: v1
kind: Namespace
metadata:
  name: traefik-system
  labels:
    app.kubernetes.io/part-of: utcp
---
apiVersion: v1
kind: Namespace
metadata:
  name: utcp-platform
  labels:
    app.kubernetes.io/part-of: utcp
    utcp.io/gateway-access: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: utcp-runtime
  labels:
    app.kubernetes.io/part-of: utcp
---
apiVersion: v1
kind: Namespace
metadata:
  name: utcp-data
  labels:
    app.kubernetes.io/part-of: utcp
---
apiVersion: v1
kind: Namespace
metadata:
  name: utcp-observability
  labels:
    app.kubernetes.io/part-of: utcp
