<?php

return [
    'catalog_version' => 't2a.2026-07-17',
    'runtime_family' => 'asterisk',
    'adapter_key' => 'asterisk-ari',
    'listener_kind' => 'asterisk-ari-events',
    'credential_type' => 'ari-basic',
    'defaults' => [
        'application_name' => env('UTCP_ASTERISK_ARI_APPLICATION', 'utcp-t0-observation'),
        'connect_timeout_ms' => (int) env('UTCP_ASTERISK_ARI_CONNECT_TIMEOUT_MS', 2000),
        'request_timeout_ms' => (int) env('UTCP_ASTERISK_ARI_REQUEST_TIMEOUT_MS', 4000),
        'websocket_handshake_timeout_ms' => (int) env('UTCP_ASTERISK_ARI_WS_HANDSHAKE_TIMEOUT_MS', 4000),
        'heartbeat_interval_ms' => (int) env('UTCP_ASTERISK_ARI_HEARTBEAT_INTERVAL_MS', 15000),
        'reconnect_min_delay_ms' => (int) env('UTCP_ASTERISK_ARI_RECONNECT_MIN_DELAY_MS', 1000),
        'reconnect_max_delay_ms' => (int) env('UTCP_ASTERISK_ARI_RECONNECT_MAX_DELAY_MS', 30000),
    ],
    'event_payload_version' => 1,
    'lease_seconds' => (int) env('UTCP_ASTERISK_ARI_LEASE_SECONDS', 45),
    'batch_size' => (int) env('UTCP_ASTERISK_ARI_BATCH_SIZE', 5),
    'poll_seconds' => (int) env('UTCP_ASTERISK_ARI_POLL_SECONDS', 5),
    'max_events_per_cycle' => 50,
    'max_payload_bytes' => (int) env('UTCP_ASTERISK_ARI_MAX_PAYLOAD_BYTES', 32768),
    'event_types' => [
        'connection_opened' => 'asterisk.ari.connection.opened',
        'connection_closed' => 'asterisk.ari.connection.closed',
        'runtime_info_observed' => 'asterisk.ari.runtime.info_observed',
        'authentication_failed' => 'asterisk.ari.authentication_failed',
        'unknown_event_observed' => 'asterisk.ari.unknown_event_observed',
        'bridge_created' => 'asterisk.ari.bridge.created',
        'bridge_destroyed' => 'asterisk.ari.bridge.destroyed',
        'channel_entered_bridge' => 'asterisk.ari.channel.entered_bridge',
        'channel_left_bridge' => 'asterisk.ari.channel.left_bridge',
        'channel_destroyed' => 'asterisk.ari.channel.destroyed',
        'stasis_start' => 'asterisk.ari.channel.stasis_start',
        'stasis_end' => 'asterisk.ari.channel.stasis_end',
    ],
    'conference' => [
        'bridge_id_prefix' => 'utcp-conf-',
        'bridge_name_prefix' => 'UTCP conference ',
        'bridge_type' => 'mixing',
        'participant_channel_id_prefix' => 'utcp-part-',
        'participant_channel_name_prefix' => 'UTCP participant ',
        'proof_endpoint' => env('UTCP_ASTERISK_CONFERENCE_PROOF_ENDPOINT', 'Local/participant@utcp-conference-proof/n'),
        'proof_originate_timeout_seconds' => (int) env('UTCP_ASTERISK_CONFERENCE_PROOF_ORIGINATE_TIMEOUT_SECONDS', 3600),
        'participant_attach_attempts' => (int) env('UTCP_ASTERISK_CONFERENCE_PARTICIPANT_ATTACH_ATTEMPTS', 8),
        'participant_attach_retry_microseconds' => (int) env('UTCP_ASTERISK_CONFERENCE_PARTICIPANT_ATTACH_RETRY_MICROSECONDS', 200000),
    ],
];
