<?php

return [
    'catalog_version' => 'c5.2026-07-15',

    'capabilities' => [
        'platform.tenants.view' => ['scope' => 'platform', 'description' => 'View tenants'],
        'platform.tenants.manage' => ['scope' => 'platform', 'description' => 'Manage tenants'],
        'platform.users.view' => ['scope' => 'platform', 'description' => 'View users'],
        'platform.users.manage' => ['scope' => 'platform', 'description' => 'Manage users'],
        'tenant.memberships.view' => ['scope' => 'tenant', 'description' => 'View tenant memberships'],
        'tenant.memberships.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant memberships'],
        'tenant.roles.view' => ['scope' => 'tenant', 'description' => 'View tenant roles'],
        'tenant.roles.assign' => ['scope' => 'tenant', 'description' => 'Assign tenant roles'],
        'runtime.nodes.view' => ['scope' => 'tenant', 'description' => 'View tenant runtime-node registry configuration'],
        'runtime.nodes.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant runtime-node registry configuration'],
        'runtime.credentials.rotate' => ['scope' => 'tenant', 'description' => 'Create, rotate, and retire runtime-node credentials'],
        'telephony.external_connectivity.view' => ['scope' => 'tenant', 'description' => 'View tenant external telephony connectivity, addresses, and caller identities'],
        'telephony.external_connectivity.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant external telephony connectivity, addresses, and caller identities'],
        'telephony.routing.view' => ['scope' => 'tenant', 'description' => 'View tenant inbound and outbound route authority'],
        'telephony.routing.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant inbound and outbound route authority'],
        'telephony.sessions.create_own' => ['scope' => 'tenant', 'description' => 'Create own control-plane telephony session'],
        'telephony.sessions.view_own' => ['scope' => 'tenant', 'description' => 'View own control-plane telephony session'],
        'telephony.sessions.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant control-plane telephony sessions'],
        'telephony.signaling.issue_own' => ['scope' => 'tenant', 'description' => 'Issue own short-lived signaling registration credential'],
        'telephony.signaling.view_own' => ['scope' => 'tenant', 'description' => 'View own signaling registration metadata'],
        'telephony.signaling.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant signaling registration metadata'],
        'telephony.conferences.view' => ['scope' => 'tenant', 'description' => 'View tenant conferences'],
        'telephony.conferences.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant conferences and desired state'],
        'telephony.conferences.join' => ['scope' => 'tenant', 'description' => 'Join open tenant conferences through an active control session'],
        'telephony.conferences.participants.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant conference participants'],
        'telephony.calls.view' => ['scope' => 'tenant', 'description' => 'View tenant calls'],
        'telephony.calls.view_own' => ['scope' => 'tenant', 'description' => 'View owned calls'],
        'telephony.calls.originate' => ['scope' => 'tenant', 'description' => 'Originate calls'],
        'telephony.calls.control' => ['scope' => 'tenant', 'description' => 'Control calls'],
        'telephony.calls.record' => ['scope' => 'tenant', 'description' => 'Control call recording'],
        'telephony.calls.manage' => ['scope' => 'tenant', 'description' => 'Manage tenant calls'],
    ],

    'roles' => [
        'platform-admin' => [
            'scope' => 'platform',
            'display_name' => 'Platform administrator',
            'capabilities' => [
                'platform.tenants.view',
                'platform.tenants.manage',
                'platform.users.view',
                'platform.users.manage',
            ],
        ],
        'tenant-admin' => [
            'scope' => 'tenant',
            'display_name' => 'Tenant administrator',
            'capabilities' => [
                'tenant.memberships.view',
                'tenant.memberships.manage',
                'tenant.roles.view',
                'tenant.roles.assign',
                'telephony.sessions.manage',
                'telephony.signaling.issue_own',
                'telephony.signaling.view_own',
                'telephony.signaling.manage',
                'telephony.conferences.view',
                'telephony.conferences.manage',
                'telephony.conferences.join',
                'telephony.conferences.participants.manage',
                'telephony.calls.view', 'telephony.calls.view_own', 'telephony.calls.originate', 'telephony.calls.control', 'telephony.calls.record', 'telephony.calls.manage',
                'runtime.nodes.view',
                'runtime.nodes.manage',
                'runtime.credentials.rotate',
                'telephony.external_connectivity.view',
                'telephony.external_connectivity.manage',
                'telephony.routing.view',
                'telephony.routing.manage',
            ],
        ],
        'tenant-member' => [
            'scope' => 'tenant',
            'display_name' => 'Tenant member',
            'capabilities' => [
                'tenant.memberships.view',
                'tenant.roles.view',
                'telephony.sessions.create_own',
                'telephony.sessions.view_own',
                'telephony.signaling.issue_own',
                'telephony.signaling.view_own',
                'telephony.conferences.view',
                'telephony.conferences.join',
            ],
        ],
    ],
];
