apiVersion: v1
kind: Service
metadata:
  name: application-runtime-sip
  namespace: utcp-runtime
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: application-runtime
    utcp.dev/runtime-selection: selected-application-runtime
spec:
  type: ClusterIP
  selector:
    utcp.dev/runtime-selection: selected-application-runtime
  ports:
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: sip
