apiVersion: v1
kind: Service
metadata:
  name: kamailio-sip-external
  namespace: utcp-platform
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Local
  ports:
    - name: sip-udp
      protocol: UDP
      port: 5060
      targetPort: sip-ext-udp
      nodePort: null
