apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - node-a
  - node-b
  - ../../components/asterisk-sip-fixtures
images:
  - name: utcp-asterisk-ari
    newName: utcp-local-registry:5000/utcp/asterisk-ari
    newTag: 0.1.0-k1-dev
