apiVersion: v1
kind: Service
metadata:
  name: kamailio-sip-external
  namespace: utcp-platform
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: kamailio
    utcp.io/exposure: v1-external-sip-lab
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  selector:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: kamailio
    utcp.io/network-role: kamailio-signaling
  ports:
    - name: sip-udp
      protocol: UDP
      port: 5060
      targetPort: sip-udp
      nodePort: 30560
