apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - api-deployment.yaml
  - api-service.yaml
  - worker-deployment.yaml
  - scheduler-deployment.yaml
  - outbox-dispatcher-deployment.yaml
  - telephony-command-worker-deployment.yaml
  - telephony-event-normalizer-deployment.yaml
  - telephony-reconciler-deployment.yaml
  - simulator-event-source-deployment.yaml
  - web-deployment.yaml
  - web-service.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
