apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-event-source
  namespace: utcp-platform
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: simulator-event-source
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: utcp
      app.kubernetes.io/component: simulator-event-source
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: utcp
        app.kubernetes.io/component: simulator-event-source
        utcp.io/network-role: worker
    spec:
      serviceAccountName: utcp-platform-app
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: simulator-event-source
          image: utcp-api
          imagePullPolicy: Always
          args:
            - simulator-event-source
          envFrom:
            - configMapRef:
                name: utcp-application-config
            - secretRef:
                name: utcp-local-data-credentials
          resources:
            requests:
              cpu: 25m
              memory: 96Mi
            limits:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
