apiVersion: apps/v1
kind: Deployment
metadata:
  name: telephony-reconciler
  namespace: utcp-platform
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: telephony-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: utcp
      app.kubernetes.io/component: telephony-reconciler
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: utcp
        app.kubernetes.io/component: telephony-reconciler
        utcp.io/network-role: worker
        utcp.io/kubernetes-api-client: "true"
        utcp.io/k5d-maintenance-client: "true"
    spec:
      serviceAccountName: utcp-kubernetes-maintenance
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 33
        runAsGroup: 33
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: reconciler
          image: utcp-api
          imagePullPolicy: Always
          args:
            - telephony-reconciler
          env:
            - name: BROADCAST_CONNECTION
              value: log
          envFrom:
            - configMapRef:
                name: utcp-application-config
            - secretRef:
                name: utcp-local-data-credentials
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 384Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
