apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: utcp-platform
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 8080
      targetPort: http
