<?php

use App\ControlPlane\Audit\AuditRepository;
use App\ControlPlane\Shared\ExecutionContext;
use App\Identity\IdentityIds;
use App\Identity\UserAccess\ResetUserPasswordService;
use App\Infrastructure\RuntimeFencing\InfrastructureConnectivityProbe;
use App\RuntimeAdapters\Asterisk\AsteriskAriEventListener;
use App\RuntimeAdapters\Asterisk\AsteriskCatalog;
use App\RuntimeAdapters\FreeSwitch\FreeSwitchCatalog;
use App\RuntimeAdapters\FreeSwitch\FreeSwitchEslEventListener;
use App\RuntimeEngine\Commands\CommandWorker;
use App\RuntimeEngine\ConferenceRecoveryMetricEventPruner;
use App\RuntimeEngine\Events\EventNormalizerWorker;
use App\RuntimeEngine\Outbox\OutboxDispatcher;
use App\RuntimeEngine\Projection\ProjectionService;
use App\RuntimeEngine\Reconciliation\ReconciliationRepository;
use App\RuntimeEngine\Reconciliation\ReconciliationWorker;
use App\Simulator\SimulatorEventSourceWorker;
use App\TelephonyDomain\Failover\ConferenceFailoverCoordinator;
use App\TelephonyDomain\Signaling\KamailioRegistrationObserver;
use App\TelephonyDomain\Signaling\KamailioRegistrationPollHealthRepository;
use App\TelephonyDomain\TelephonyDomainService;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Schedule;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('identity:bootstrap-local
    {--email=admin@utcp.local.test : Local administrator email}
    {--display-name=UTCP Local Administrator : Local administrator display name}
    {--password= : One-time bootstrap password; generated by wrapper when omitted}
    {--tenant-slug=local : Optional local tenant slug}
    {--tenant-name=Local Tenant : Optional local tenant display name}', function (AuditRepository $audit): int {
    $email = Str::lower((string) $this->option('email'));
    $displayName = trim((string) $this->option('display-name')) ?: 'UTCP Local Administrator';
    $password = (string) ($this->option('password') ?: 'utcp-'.bin2hex(random_bytes(12)));
    $tenantSlug = Str::slug((string) $this->option('tenant-slug')) ?: 'local';
    $tenantName = trim((string) $this->option('tenant-name')) ?: 'Local Tenant';

    $existingAdmin = DB::table('platform_role_assignments')
        ->where('role_key', 'platform-admin')
        ->value('user_id');

    if (is_string($existingAdmin)) {
        $this->info('A platform administrator already exists; bootstrap did not modify credentials.');

        return 0;
    }

    DB::transaction(function () use ($audit, $email, $displayName, $password, $tenantSlug, $tenantName): void {
        $now = now();
        $user = DB::table('users')->where('normalized_email', $email)->first();
        $userId = is_object($user) ? $user->id : IdentityIds::new();

        if (! is_object($user)) {
            DB::table('users')->insert([
                'id' => $userId,
                'email' => $email,
                'normalized_email' => $email,
                'display_name' => $displayName,
                'password' => Hash::make($password),
                'status' => 'active',
                'password_change_required' => false,
                'session_version' => 1,
                'password_changed_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        DB::table('platform_role_assignments')->insert([
            'id' => IdentityIds::new(),
            'user_id' => $userId,
            'role_key' => 'platform-admin',
            'assigned_by_user_id' => null,
            'created_at' => $now,
        ]);

        $tenant = DB::table('tenants')->where('slug', $tenantSlug)->first();
        $tenantId = is_object($tenant) ? $tenant->id : IdentityIds::new();
        if (! is_object($tenant)) {
            DB::table('tenants')->insert([
                'id' => $tenantId,
                'slug' => $tenantSlug,
                'display_name' => $tenantName,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        $membership = DB::table('tenant_memberships')->where('tenant_id', $tenantId)->where('user_id', $userId)->first();
        $membershipId = is_object($membership) ? $membership->id : IdentityIds::new();
        if (! is_object($membership)) {
            DB::table('tenant_memberships')->insert([
                'id' => $membershipId,
                'tenant_id' => $tenantId,
                'user_id' => $userId,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        if (! DB::table('tenant_role_assignments')->where('membership_id', $membershipId)->where('role_key', 'tenant-admin')->exists()) {
            DB::table('tenant_role_assignments')->insert([
                'id' => IdentityIds::new(),
                'membership_id' => $membershipId,
                'role_key' => 'tenant-admin',
                'assigned_by_user_id' => null,
                'created_at' => $now,
            ]);
        }

        $context = ExecutionContext::system();
        $audit->append($context, 'identity.bootstrap.platform_admin_created', 'user', $userId, [
            'email_hash' => hash('sha256', $email),
        ]);
        $audit->append($context, 'identity.bootstrap.local_tenant_ready', 'tenant', $tenantId, [
            'slug' => $tenantSlug,
        ]);
    });

    $this->info('Local platform administrator bootstrap is ready. Credentials were not printed.');

    return 0;
})->purpose('Create the first local platform administrator when none exists.');

Artisan::command('utcp:user-access:reset-password
    {--user= : Exact user email address or UUID}
    {--reason= : Operator reason for audit evidence}
    {--expires-in=30 : Temporary password expiration in minutes}
    {--show-password : Print the generated temporary password once}', function (ResetUserPasswordService $reset): int {
    $selector = trim((string) $this->option('user'));
    $reason = trim((string) $this->option('reason'));
    $expiresIn = filter_var($this->option('expires-in'), FILTER_VALIDATE_INT);

    if ($selector === '') {
        $this->error('The --user option is required.');

        return 2;
    }
    if ($reason === '') {
        $this->error('The --reason option is required.');

        return 2;
    }
    if ($expiresIn === false) {
        $this->error('The --expires-in option must be an integer number of minutes.');

        return 2;
    }

    try {
        $result = $reset->resetFromConsole($selector, $reason, (int) $expiresIn);
    } catch (Throwable $exception) {
        $this->error($exception->getMessage());

        return 1;
    }

    $expires = $result->expiresAt
        ->setTimezone(config('app.timezone'))
        ->format('Y-m-d H:i:s e');

    $this->line('Temporary login credential issued.');
    $this->newLine();
    $this->line('User: '.$result->userDisplay);
    $this->line('Expires: '.$expires);
    $this->line('Password change required: yes');
    $this->line('Existing sessions revoked: '.($result->sessionsRevoked ? 'yes' : 'no'));

    if ((bool) $this->option('show-password')) {
        $this->newLine();
        $this->line('Temporary password: '.$result->temporaryPassword);
    } else {
        $this->line('Temporary password displayed: no');
    }

    return 0;
});

Artisan::command('identity:status', function (): int {
    $tables = ['users', 'tenants', 'tenant_memberships', 'roles', 'capabilities', 'sessions'];

    foreach ($tables as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }

        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('users')) {
        DB::table('users')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('users_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('tenants')) {
        DB::table('tenants')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('tenants_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('tenant_memberships')) {
        DB::table('tenant_memberships')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('memberships_status_'.$row->status.'='.$row->count));
    }

    $this->line('catalog_version='.config('identity.catalog_version'));

    return 0;
})->purpose('Report non-sensitive identity and tenancy status.');

Artisan::command('runtime-registry:status', function (): int {
    $tables = [
        'runtime_nodes',
        'runtime_node_endpoints',
        'runtime_node_credentials',
        'runtime_node_capabilities',
    ];

    foreach ($tables as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }

        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('runtime_nodes')) {
        DB::table('runtime_nodes')
            ->select('runtime_family', DB::raw('count(*) as count'))
            ->groupBy('runtime_family')
            ->orderBy('runtime_family')
            ->get()
            ->each(fn (object $row) => $this->line('nodes_family_'.$row->runtime_family.'='.$row->count));

        DB::table('runtime_nodes')
            ->select('desired_state', DB::raw('count(*) as count'))
            ->groupBy('desired_state')
            ->orderBy('desired_state')
            ->get()
            ->each(fn (object $row) => $this->line('nodes_desired_'.$row->desired_state.'='.$row->count));

        DB::table('runtime_nodes')
            ->select('observed_state', DB::raw('count(*) as count'))
            ->groupBy('observed_state')
            ->orderBy('observed_state')
            ->get()
            ->each(fn (object $row) => $this->line('nodes_observed_'.$row->observed_state.'='.$row->count));
    }

    if (Schema::hasTable('runtime_node_endpoints')) {
        DB::table('runtime_node_endpoints')
            ->select('purpose', DB::raw('count(*) as count'))
            ->groupBy('purpose')
            ->orderBy('purpose')
            ->get()
            ->each(fn (object $row) => $this->line('endpoints_purpose_'.$row->purpose.'='.$row->count));
    }

    if (Schema::hasTable('runtime_node_credentials')) {
        DB::table('runtime_node_credentials')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('credentials_status_'.$row->status.'='.$row->count));
    }

    $this->line('catalog_version='.config('runtime_registry.catalog_version'));

    return 0;
})->purpose('Report non-sensitive runtime registry status.');

Artisan::command('runtime-engine:outbox-dispatcher {--once : Process one batch and exit}', function (OutboxDispatcher $dispatcher): int {
    $workerId = gethostname().':outbox:'.getmypid();
    do {
        $dispatcher->dispatchOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the automatic transactional outbox dispatcher.');

Artisan::command('runtime-engine:command-worker {--once : Process one batch and exit}', function (CommandWorker $worker): int {
    $workerId = gethostname().':command:'.getmypid();
    do {
        $worker->workOnce(
            $workerId,
            (int) config('runtime_engine.batch_size', 10),
            excludeOperationTypes: [
                (string) config('telephony_domain.operation_types.runtime_fence'),
                (string) config('telephony_domain.operation_types.runtime_node_restore'),
                (string) config('telephony_domain.operation_types.runtime_node_provision'),
                (string) config('telephony_domain.operation_types.runtime_node_deprovision'),
            ],
        );
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the generic runtime-operation command worker.');

Artisan::command('runtime-engine:infrastructure-worker {--once : Process one infrastructure-operation batch and exit}', function (CommandWorker $worker): int {
    $workerId = gethostname().':infrastructure:'.getmypid();
    do {
        $worker->workOnce(
            $workerId,
            (int) config('runtime_engine.batch_size', 10),
            includeOperationTypes: [
                (string) config('telephony_domain.operation_types.runtime_fence'),
                (string) config('telephony_domain.operation_types.runtime_node_restore'),
                (string) config('telephony_domain.operation_types.runtime_node_provision'),
                (string) config('telephony_domain.operation_types.runtime_node_deprovision'),
            ],
        );
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the dedicated runtime infrastructure-operation worker.');

Artisan::command('runtime-engine:infrastructure-probe {--once : Run one read-only Kubernetes infrastructure probe and exit}', function (InfrastructureConnectivityProbe $probe): int {
    if (! $this->option('once')) {
        $this->error('The infrastructure probe is a bounded diagnostic and requires --once.');

        return 2;
    }

    $result = $probe->runOnce();
    if (($result['status'] ?? null) !== 'ok') {
        $this->error('infrastructure_probe_status=failed');
        $this->error('reason='.(string) ($result['reason'] ?? 'failed'));

        return 1;
    }

    foreach ([
        'runtime_node_slug',
        'namespace',
        'deployment',
        'desired_replicas',
        'status_replicas',
        'available_replicas',
        'owned_pod_count',
    ] as $key) {
        $this->line($key.'='.(string) $result[$key]);
    }

    return 0;
})->purpose('Run a read-only Kubernetes connectivity probe for a registered RuntimeNode workload.');

Artisan::command('runtime-engine:event-normalizer {--once : Process one batch and exit}', function (EventNormalizerWorker $worker): int {
    $workerId = gethostname().':normalizer:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the generic runtime-event normalizer.');

Artisan::command('runtime-engine:reconciler {--once : Process one batch and exit}', function (ReconciliationWorker $worker): int {
    $workerId = gethostname().':reconciler:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 10));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the generic reconciliation worker.');

Artisan::command('kamailio-registration:observer {--once : Collect one snapshot and exit} {--sleep=5 : Seconds between snapshots}', function (KamailioRegistrationObserver $observer, KamailioRegistrationPollHealthRepository $pollHealth): int {
    $owner = gethostname().':kamailio-registration-observer:'.getmypid();
    $sleep = max(1, (int) $this->option('sleep'));
    do {
        try {
            $result = $observer->pollOnce($owner);
            $this->line('kamailio_registration_observer_status='.$result['status']);
            $this->line('kamailio_registration_observer_receipts='.$result['receipts']);
            $this->line('kamailio_registration_observer_checkpoint_advanced='.($result['checkpoint_advanced'] ? '1' : '0'));
            $pollHealth->recordSuccess();
        } catch (Throwable $exception) {
            $pollHealth->recordFailure();
            Log::warning('kamailio registration observer poll failed', [
                'component' => 'kamailio-registration-observer',
                'result' => 'poll_failed',
            ]);
            if ($this->option('once')) {
                throw $exception;
            }
        }
        if (! $this->option('once')) {
            sleep($sleep);
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Collect fenced Kamailio usrloc snapshots into canonical C3 receipts.');

Artisan::command('runtime-engine:derive-stale-observations', function (ProjectionService $projection): int {
    $count = $projection->markStale((int) config('runtime_engine.stale_observation_seconds', 300));
    $this->line('stale_observations_marked='.$count);

    return 0;
})->purpose('Derive stale runtime-node observations without manual state authority.');

Artisan::command('runtime-engine:prune-conference-recovery-metric-events {--once : Run one bounded pruning pass and exit}', function (ConferenceRecoveryMetricEventPruner $pruner): int {
    if (! $this->option('once')) {
        $this->error('conference_recovery_metric_event_prune_status=failed');
        $this->error('reason=once_required');

        return 2;
    }

    try {
        $result = $pruner->pruneExpired(
            (int) config('runtime_engine.conference_recovery_metric_event_retention_days', 7),
            (int) config('runtime_engine.conference_recovery_metric_event_prune_batch_size', 1000),
            (int) config('runtime_engine.conference_recovery_metric_event_prune_max_batches_per_run', 10),
        );
    } catch (Throwable) {
        Log::warning('conference recovery metric event pruning failed', [
            'component' => 'conference-recovery-metric-event-pruner',
            'result' => 'failed',
            'rows_deleted' => 0,
            'batches' => 0,
            'remaining_backlog' => false,
        ]);
        $this->error('conference_recovery_metric_event_prune_status=failed');

        return 1;
    }

    Log::info('conference recovery metric event pruning completed', [
        'component' => 'conference-recovery-metric-event-pruner',
        'result' => $result['result'],
        'rows_deleted' => $result['rows_deleted'],
        'batches' => $result['batches_completed'],
        'remaining_backlog' => $result['eligible_backlog_remaining'],
    ]);

    $this->line('conference_recovery_metric_event_prune_status='.$result['result']);
    $this->line('rows_deleted='.$result['rows_deleted']);
    $this->line('batches_completed='.$result['batches_completed']);
    $this->line('eligible_backlog_remaining='.($result['eligible_backlog_remaining'] ? '1' : '0'));

    return in_array($result['result'], ['succeeded', 'noop', 'backlog_remaining'], true) ? 0 : 1;
})->purpose('Prune expired conference recovery metric events with bounded retention.');

Artisan::command('runtime-engine:status', function (): int {
    $tables = [
        'runtime_operations',
        'control_plane_outbox_messages',
        'runtime_event_receipts',
        'runtime_observations',
        'runtime_projection_checkpoints',
        'runtime_reconciliation_states',
    ];

    foreach ($tables as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }

        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('runtime_operations')) {
        DB::table('runtime_operations')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('operations_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('control_plane_outbox_messages') && Schema::hasColumn('control_plane_outbox_messages', 'dispatch_status')) {
        DB::table('control_plane_outbox_messages')
            ->select('dispatch_status', DB::raw('count(*) as count'))
            ->groupBy('dispatch_status')
            ->orderBy('dispatch_status')
            ->get()
            ->each(fn (object $row) => $this->line('outbox_dispatch_'.$row->dispatch_status.'='.$row->count));
    }

    if (Schema::hasTable('runtime_event_receipts')) {
        DB::table('runtime_event_receipts')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('event_receipts_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('runtime_reconciliation_states')) {
        DB::table('runtime_reconciliation_states')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('reconciliation_status_'.$row->status.'='.$row->count));
    }

    $this->line('catalog_version='.config('runtime_engine.catalog_version'));

    return 0;
})->purpose('Report non-sensitive runtime engine status.');

Artisan::command('simulator:ensure-targets', function (ReconciliationRepository $repository): int {
    $count = 0;
    DB::table('runtime_nodes')
        ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
        ->whereIn('desired_state', ['active', 'draining'])
        ->orderBy('id')
        ->get()
        ->each(function (object $node) use ($repository, &$count): void {
            if (DB::table('simulator_profiles')->where('runtime_node_id', $node->id)->exists()) {
                $repository->ensureTarget((string) $node->tenant_id, 'runtime_node', (string) $node->id, (int) $node->configuration_version);
                $count++;
            }
        });
    $this->line('simulator_reconciliation_targets_ensured='.$count);

    return 0;
})->purpose('Automatically ensure reconciliation targets for active deterministic simulator nodes.');

Artisan::command('simulator:event-source {--once : Publish one batch and exit}', function (SimulatorEventSourceWorker $worker): int {
    $workerId = gethostname().':simulator-events:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('simulator.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('simulator.poll_seconds', 3));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the deterministic simulator scheduled-event source.');

Artisan::command('asterisk-ari:ensure-targets', function (ReconciliationRepository $repository, AsteriskCatalog $catalog): int {
    $count = 0;
    DB::table('runtime_nodes')
        ->where('adapter_key', $catalog->adapterKey())
        ->whereIn('desired_state', ['active', 'draining'])
        ->orderBy('id')
        ->get()
        ->each(function (object $node) use ($repository, &$count): void {
            $repository->ensureTarget((string) $node->tenant_id, 'runtime_node', (string) $node->id, (int) $node->configuration_version);
            $count++;
        });
    $this->line('asterisk_ari_reconciliation_targets_ensured='.$count);

    return 0;
})->purpose('Automatically ensure reconciliation targets for active Asterisk ARI runtime nodes.');

Artisan::command('asterisk-ari:events {--once : Claim active nodes and process one listener cycle}', function (AsteriskAriEventListener $listener): int {
    $workerId = gethostname().':asterisk-ari-events:'.getmypid();
    do {
        $listener->workOnce($workerId, (int) config('asterisk_ari.batch_size', 5));
        if (! $this->option('once')) {
            sleep((int) config('asterisk_ari.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the Asterisk ARI event listener with dynamic RuntimeNode discovery.');

Artisan::command('freeswitch-esl:ensure-targets', function (ReconciliationRepository $repository, FreeSwitchCatalog $catalog): int {
    $count = 0;
    DB::table('runtime_nodes')->where('adapter_key', $catalog->adapterKey())->whereIn('desired_state', ['active', 'draining'])->orderBy('id')->get()->each(function (object $node) use ($repository, &$count): void {
        $repository->ensureTarget((string) $node->tenant_id, 'runtime_node', (string) $node->id, (int) $node->configuration_version);
        $count++;
    });
    $this->line('freeswitch_esl_reconciliation_targets_ensured='.$count);

    return 0;
})->purpose('Automatically ensure reconciliation targets for managed FreeSWITCH ESL runtime nodes.');

Artisan::command('freeswitch-esl:events {--once : Claim active nodes and process one listener cycle}', function (FreeSwitchEslEventListener $listener): int {
    $workerId = gethostname().':freeswitch-esl-events:'.getmypid();
    do {
        $listener->workOnce($workerId);
        if (! $this->option('once')) {
            sleep(5);
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the FreeSWITCH ESL event listener with dynamic RuntimeNode discovery.');

Artisan::command('asterisk-ari:status', function (AsteriskCatalog $catalog): int {
    if (! Schema::hasTable('runtime_nodes')) {
        $this->line('asterisk_nodes=missing');

        return 0;
    }

    $nodeIds = DB::table('runtime_nodes')
        ->where('adapter_key', $catalog->adapterKey())
        ->pluck('id')
        ->map(fn (mixed $id): string => (string) $id)
        ->all();

    $this->line('asterisk_nodes='.count($nodeIds));
    DB::table('runtime_nodes')
        ->where('adapter_key', $catalog->adapterKey())
        ->select('desired_state', DB::raw('count(*) as count'))
        ->groupBy('desired_state')
        ->orderBy('desired_state')
        ->get()
        ->each(fn (object $row) => $this->line('asterisk_desired_'.$row->desired_state.'='.$row->count));
    DB::table('runtime_nodes')
        ->where('adapter_key', $catalog->adapterKey())
        ->select('observed_state', DB::raw('count(*) as count'))
        ->groupBy('observed_state')
        ->orderBy('observed_state')
        ->get()
        ->each(fn (object $row) => $this->line('asterisk_observed_'.$row->observed_state.'='.$row->count));

    if (Schema::hasTable('runtime_listener_leases')) {
        $this->line('asterisk_listener_claimed='.DB::table('runtime_listener_leases')->where('listener_kind', $catalog->listenerKind())->where('status', 'claimed')->where('lease_expires_at', '>', now())->count());
    }
    if (Schema::hasTable('runtime_event_connection_epochs')) {
        $this->line('asterisk_open_epochs='.DB::table('runtime_event_connection_epochs')->where('adapter_key', $catalog->adapterKey())->where('status', 'open')->count());
    }
    if (Schema::hasTable('runtime_operations') && $nodeIds !== []) {
        DB::table('runtime_operations')
            ->whereIn('runtime_node_id', $nodeIds)
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('asterisk_operations_'.$row->status.'='.$row->count));
        $oldestPending = DB::table('runtime_operations')
            ->whereIn('runtime_node_id', $nodeIds)
            ->whereIn('status', ['pending', 'retry_scheduled', 'leased', 'running'])
            ->min('created_at');
        $this->line('asterisk_oldest_pending_operation_age_seconds='.(is_string($oldestPending) ? (int) now()->diffInSeconds($oldestPending, true) : 0));
    }
    if (Schema::hasTable('runtime_event_receipts') && $nodeIds !== []) {
        DB::table('runtime_event_receipts')
            ->whereIn('runtime_node_id', $nodeIds)
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('asterisk_receipts_'.$row->status.'='.$row->count));
        $this->line('asterisk_authentication_failures_recent='.DB::table('runtime_event_receipts')->whereIn('runtime_node_id', $nodeIds)->where('event_type', $catalog->eventType('authentication_failed'))->where('received_at', '>=', now()->subHour())->count());
    }
    $this->line('catalog_version='.config('asterisk_ari.catalog_version'));

    return 0;
})->purpose('Report safe aggregate Asterisk ARI adapter status.');

Artisan::command('simulator:status', function (): int {
    foreach (['simulator_profiles', 'simulator_states', 'simulator_scheduled_events'] as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }
        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('runtime_nodes')) {
        $this->line('simulator_nodes='.DB::table('runtime_nodes')->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))->count());
        DB::table('runtime_nodes')
            ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
            ->select('desired_state', DB::raw('count(*) as count'))
            ->groupBy('desired_state')
            ->orderBy('desired_state')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_desired_'.$row->desired_state.'='.$row->count));
        DB::table('runtime_nodes')
            ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
            ->select('observed_state', DB::raw('count(*) as count'))
            ->groupBy('observed_state')
            ->orderBy('observed_state')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_observed_'.$row->observed_state.'='.$row->count));
    }

    if (Schema::hasTable('simulator_scheduled_events')) {
        DB::table('simulator_scheduled_events')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_events_status_'.$row->status.'='.$row->count));

        DB::table('simulator_scheduled_events')
            ->select('status', DB::raw('count(*) as count'))
            ->where('due_at', '<=', now())
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_due_events_status_'.$row->status.'='.$row->count));

        $oldestDueAt = DB::table('simulator_scheduled_events')
            ->whereIn('status', ['pending', 'retry_scheduled'])
            ->where('due_at', '<=', now())
            ->min('due_at');
        $age = is_string($oldestDueAt) ? max(0, now()->diffInSeconds($oldestDueAt, true)) : 0;
        $this->line('simulator_oldest_due_event_age_seconds='.(int) $age);
    }

    if (Schema::hasTable('simulator_profiles')) {
        DB::table('simulator_profiles')
            ->select('scenario_key', DB::raw('count(*) as count'))
            ->groupBy('scenario_key')
            ->orderBy('scenario_key')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_scenario_'.$row->scenario_key.'='.$row->count));
    }

    if (Schema::hasTable('runtime_reconciliation_states') && Schema::hasTable('runtime_nodes')) {
        $simulatorNodeIds = DB::table('runtime_nodes')
            ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
            ->pluck('id')
            ->map(fn (mixed $id): string => (string) $id)
            ->all();

        DB::table('runtime_reconciliation_states')
            ->where('runtime_reconciliation_states.target_type', 'runtime_node')
            ->whereIn('runtime_reconciliation_states.target_id', $simulatorNodeIds)
            ->select('runtime_reconciliation_states.status', DB::raw('count(*) as count'))
            ->groupBy('runtime_reconciliation_states.status')
            ->orderBy('runtime_reconciliation_states.status')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_reconciliation_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('runtime_operations') && Schema::hasTable('runtime_nodes')) {
        $simulatorNodeIds = DB::table('runtime_nodes')
            ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
            ->pluck('id')
            ->map(fn (mixed $id): string => (string) $id)
            ->all();

        DB::table('runtime_operations')
            ->whereIn('runtime_operations.runtime_node_id', $simulatorNodeIds)
            ->select('runtime_operations.status', DB::raw('count(*) as count'))
            ->groupBy('runtime_operations.status')
            ->orderBy('runtime_operations.status')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_operations_'.$row->status.'='.$row->count));

        DB::table('runtime_operations')
            ->whereIn('runtime_operations.runtime_node_id', $simulatorNodeIds)
            ->where('runtime_operations.status', 'terminal_failed')
            ->select(DB::raw("coalesce(runtime_operations.last_failure_class, 'none') as failure_class"), DB::raw('count(*) as count'))
            ->groupBy('runtime_operations.last_failure_class')
            ->orderBy('failure_class')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_terminal_failure_'.$row->failure_class.'='.$row->count));
    }
    $this->line('catalog_version='.config('simulator.catalog_version'));

    return 0;
})->purpose('Report non-sensitive deterministic simulator status.');

Artisan::command('telephony-domain:expire-sessions', function (TelephonyDomainService $domain): int {
    $this->line('telephony_sessions_expired='.$domain->expireDueSessions());

    return 0;
})->purpose('Expire due control-plane telephony sessions and request participant reconciliation.');

Artisan::command('telephony-domain:expire-recoverable-participants', function (TelephonyDomainService $domain): int {
    $this->line('telephony_domain_recoverable_participants_expired='.$domain->expireRecoverableParticipants());

    return 0;
})->purpose('Expire abandoned self-admission participation after its canonical recovery grace.');

Artisan::command('telephony-domain:ensure-targets', function (ReconciliationRepository $repository): int {
    $count = 0;
    if (Schema::hasTable('conferences')) {
        DB::table('conferences')
            ->whereIn('desired_state', ['open', 'draining', 'closed'])
            ->orderBy('id')
            ->get()
            ->each(function (object $conference) use ($repository, &$count): void {
                $repository->ensureTarget((string) $conference->tenant_id, 'conference', (string) $conference->id, (int) $conference->configuration_generation);
                $count++;
            });
    }
    if (Schema::hasTable('conference_participants')) {
        DB::table('conference_participants')
            ->orderBy('id')
            ->get()
            ->each(function (object $participant) use ($repository, &$count): void {
                $conference = DB::table('conferences')->where('id', $participant->conference_id)->first();
                $conferenceGeneration = max(1, (int) ($conference->configuration_generation ?? 1));
                $participantGeneration = ($conferenceGeneration * 2) + ($participant->desired_state === 'removed' ? 1 : 0);
                $repository->ensureTarget((string) $participant->tenant_id, 'conference_participant', (string) $participant->id, $participantGeneration);
                $count++;
            });
    }
    if (Schema::hasTable('call_legs')) {
        DB::table('call_legs')
            ->where('direction', 'outbound')
            ->whereNotIn('observed_state', ['completed', 'failed', 'cancelled'])
            ->orderBy('id')
            ->get()
            ->each(function (object $leg) use ($repository, &$count): void {
                $repository->ensureTarget((string) $leg->tenant_id, 'call_leg_origination', (string) $leg->id, 1);
                $count++;
            });
    }
    $this->line('telephony_domain_reconciliation_targets_ensured='.$count);

    return 0;
})->purpose('Ensure conference and participant reconciliation targets without manual execution authority.');

Artisan::command('telephony-domain:failover-coordinator {--once : Run one bounded failover coordinator sweep and exit}', function (ConferenceFailoverCoordinator $coordinator): int {
    do {
        $summary = $coordinator->sweepOnce(gethostname().':telephony-domain-failover-coordinator:'.getmypid(), (int) config('runtime_engine.batch_size', 10));
        foreach ($summary as $key => $value) {
            $this->line('telephony_domain_failover_'.$key.'='.$value);
        }
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the automatic conference failover coordinator without manual target selection.');

Artisan::command('telephony-domain:retire-closed-bindings {--once : Run one bounded closed-conference binding retirement sweep and exit} {--batch=100 : Maximum closed-conference bindings to evaluate}', function (TelephonyDomainService $domain): int {
    $batch = filter_var($this->option('batch'), FILTER_VALIDATE_INT);
    if ($batch === false || $batch < 1) {
        $this->error('The --batch option must be a positive integer.');

        return 2;
    }

    $summary = $domain->retireClosedConferenceBindings((int) $batch);
    foreach ($summary as $key => $value) {
        $this->line('telephony_domain_closed_binding_retirement_'.$key.'='.$value);
    }

    return 0;
})->purpose('Run the automatic closed-conference RuntimeBinding retirement sweep without manual target selection.');

Artisan::command('telephony-domain:reclaim-orphan-participant-channels {--once : Run one bounded orphan participant channel discovery sweep and exit} {--batch=100 : Maximum removed participants to evaluate}', function (TelephonyDomainService $domain): int {
    $batch = filter_var($this->option('batch'), FILTER_VALIDATE_INT);
    if ($batch === false || $batch < 1) {
        $this->error('The --batch option must be a positive integer.');

        return 2;
    }

    $summary = $domain->reclaimOrphanParticipantChannels((int) $batch);
    foreach ($summary as $key => $value) {
        $this->line('telephony_domain_orphan_participant_channel_reclamation_'.$key.'='.$value);
    }

    return 0;
})->purpose('Run the automatic orphan participant channel discovery sweep without manual target selection.');

Artisan::command('telephony-domain:status', function (): int {
    foreach (['telephony_sessions', 'conferences', 'conference_participants'] as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }
        $this->line($table.'_count='.DB::table($table)->count());
    }
    if (Schema::hasTable('telephony_sessions')) {
        DB::table('telephony_sessions')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('sessions_status_'.$row->status.'='.$row->count));
        $this->line('sessions_expired_active='.DB::table('telephony_sessions')->where('status', 'active')->where('expires_at', '<=', now())->count());
    }
    if (Schema::hasTable('conferences')) {
        DB::table('conferences')
            ->select('desired_state', DB::raw('count(*) as count'))
            ->groupBy('desired_state')
            ->orderBy('desired_state')
            ->get()
            ->each(fn (object $row) => $this->line('conferences_desired_'.$row->desired_state.'='.$row->count));
        DB::table('conferences')
            ->select('observed_state', DB::raw('count(*) as count'))
            ->groupBy('observed_state')
            ->orderBy('observed_state')
            ->get()
            ->each(fn (object $row) => $this->line('conferences_observed_'.$row->observed_state.'='.$row->count));
    }
    if (Schema::hasTable('conference_participants')) {
        DB::table('conference_participants')
            ->select('desired_state', DB::raw('count(*) as count'))
            ->groupBy('desired_state')
            ->orderBy('desired_state')
            ->get()
            ->each(fn (object $row) => $this->line('participants_desired_'.$row->desired_state.'='.$row->count));
        DB::table('conference_participants')
            ->select('observed_state', DB::raw('count(*) as count'))
            ->groupBy('observed_state')
            ->orderBy('observed_state')
            ->get()
            ->each(fn (object $row) => $this->line('participants_observed_'.$row->observed_state.'='.$row->count));
    }
    if (Schema::hasTable('runtime_operations')) {
        $operationTypes = [
            config('telephony_domain.operation_types.conference_ensure'),
            config('telephony_domain.operation_types.conference_close'),
            config('telephony_domain.operation_types.participant_ensure'),
            config('telephony_domain.operation_types.participant_remove'),
        ];
        $oldestPending = DB::table('runtime_operations')
            ->whereIn('operation_type', $operationTypes)
            ->whereIn('status', ['pending', 'retry_scheduled', 'leased', 'running'])
            ->min('created_at');
        $this->line('telephony_domain_oldest_pending_operation_age_seconds='.(is_string($oldestPending) ? (int) now()->diffInSeconds($oldestPending, true) : 0));

        DB::table('runtime_operations')
            ->whereIn('operation_type', $operationTypes)
            ->where('status', 'terminal_failed')
            ->select(DB::raw("coalesce(last_failure_class, 'none') as failure_class"), DB::raw('count(*) as count'))
            ->groupBy('last_failure_class')
            ->orderBy('failure_class')
            ->get()
            ->each(fn (object $row) => $this->line('telephony_domain_terminal_failure_'.$row->failure_class.'='.$row->count));
    }
    if (Schema::hasTable('runtime_reconciliation_states')) {
        DB::table('runtime_reconciliation_states')
            ->whereIn('target_type', ['conference', 'conference_participant'])
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('telephony_domain_reconciliation_'.$row->status.'='.$row->count));
    }
    $this->line('catalog_version='.config('telephony_domain.catalog_version'));

    return 0;
})->purpose('Report safe aggregate telephony session and conference-domain status.');

Schedule::command('runtime-engine:outbox-dispatcher --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:command-worker --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:event-normalizer --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:reconciler --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:derive-stale-observations')->everyFiveMinutes()->withoutOverlapping();
Schedule::command('runtime-engine:prune-conference-recovery-metric-events --once')->hourly()->withoutOverlapping();
Schedule::command('simulator:ensure-targets')->everyMinute()->withoutOverlapping();
Schedule::command('simulator:event-source --once')->everyMinute()->withoutOverlapping();
Schedule::command('asterisk-ari:ensure-targets')->everyMinute()->withoutOverlapping();
Schedule::command('freeswitch-esl:ensure-targets')->everyMinute()->withoutOverlapping();
Schedule::command('telephony-domain:expire-sessions')->everyMinute()->withoutOverlapping();
Schedule::command('telephony-domain:expire-recoverable-participants')->everyMinute()->withoutOverlapping();
Schedule::command('telephony-domain:ensure-targets')->everyMinute()->withoutOverlapping();
Schedule::command('telephony-domain:failover-coordinator --once')->everyMinute()->withoutOverlapping();
Schedule::command('telephony-domain:retire-closed-bindings --once')->everyMinute()->withoutOverlapping();
Schedule::command('telephony-domain:reclaim-orphan-participant-channels --once')->everyMinute()->withoutOverlapping();
