<?php

use App\ControlPlane\Audit\AuditRepository;
use App\ControlPlane\Shared\ExecutionContext;
use App\Identity\IdentityIds;
use App\RuntimeEngine\Commands\CommandWorker;
use App\RuntimeEngine\Events\EventNormalizerWorker;
use App\RuntimeEngine\Outbox\OutboxDispatcher;
use App\RuntimeEngine\Projection\ProjectionService;
use App\RuntimeEngine\Reconciliation\ReconciliationRepository;
use App\RuntimeEngine\Reconciliation\ReconciliationWorker;
use App\Simulator\SimulatorEventSourceWorker;
use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Schedule;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('identity:bootstrap-local
    {--email=admin@utcp.local.test : Local administrator email}
    {--display-name=UTCP Local Administrator : Local administrator display name}
    {--password= : One-time bootstrap password; generated by wrapper when omitted}
    {--tenant-slug=local : Optional local tenant slug}
    {--tenant-name=Local Tenant : Optional local tenant display name}', function (AuditRepository $audit): int {
    $email = Str::lower((string) $this->option('email'));
    $displayName = trim((string) $this->option('display-name')) ?: 'UTCP Local Administrator';
    $password = (string) ($this->option('password') ?: 'utcp-'.bin2hex(random_bytes(12)));
    $tenantSlug = Str::slug((string) $this->option('tenant-slug')) ?: 'local';
    $tenantName = trim((string) $this->option('tenant-name')) ?: 'Local Tenant';

    $existingAdmin = DB::table('platform_role_assignments')
        ->where('role_key', 'platform-admin')
        ->value('user_id');

    if (is_string($existingAdmin)) {
        $this->info('A platform administrator already exists; bootstrap did not modify credentials.');

        return 0;
    }

    DB::transaction(function () use ($audit, $email, $displayName, $password, $tenantSlug, $tenantName): void {
        $now = now();
        $user = DB::table('users')->where('normalized_email', $email)->first();
        $userId = is_object($user) ? $user->id : IdentityIds::new();

        if (! is_object($user)) {
            DB::table('users')->insert([
                'id' => $userId,
                'email' => $email,
                'normalized_email' => $email,
                'display_name' => $displayName,
                'password' => Hash::make($password),
                'status' => 'active',
                'password_change_required' => false,
                'session_version' => 1,
                'password_changed_at' => $now,
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        DB::table('platform_role_assignments')->insert([
            'id' => IdentityIds::new(),
            'user_id' => $userId,
            'role_key' => 'platform-admin',
            'assigned_by_user_id' => null,
            'created_at' => $now,
        ]);

        $tenant = DB::table('tenants')->where('slug', $tenantSlug)->first();
        $tenantId = is_object($tenant) ? $tenant->id : IdentityIds::new();
        if (! is_object($tenant)) {
            DB::table('tenants')->insert([
                'id' => $tenantId,
                'slug' => $tenantSlug,
                'display_name' => $tenantName,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        $membership = DB::table('tenant_memberships')->where('tenant_id', $tenantId)->where('user_id', $userId)->first();
        $membershipId = is_object($membership) ? $membership->id : IdentityIds::new();
        if (! is_object($membership)) {
            DB::table('tenant_memberships')->insert([
                'id' => $membershipId,
                'tenant_id' => $tenantId,
                'user_id' => $userId,
                'status' => 'active',
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }

        if (! DB::table('tenant_role_assignments')->where('membership_id', $membershipId)->where('role_key', 'tenant-admin')->exists()) {
            DB::table('tenant_role_assignments')->insert([
                'id' => IdentityIds::new(),
                'membership_id' => $membershipId,
                'role_key' => 'tenant-admin',
                'assigned_by_user_id' => null,
                'created_at' => $now,
            ]);
        }

        $context = ExecutionContext::system();
        $audit->append($context, 'identity.bootstrap.platform_admin_created', 'user', $userId, [
            'email_hash' => hash('sha256', $email),
        ]);
        $audit->append($context, 'identity.bootstrap.local_tenant_ready', 'tenant', $tenantId, [
            'slug' => $tenantSlug,
        ]);
    });

    $this->info('Local platform administrator bootstrap is ready. Credentials were not printed.');

    return 0;
})->purpose('Create the first local platform administrator when none exists.');

Artisan::command('identity:status', function (): int {
    $tables = ['users', 'tenants', 'tenant_memberships', 'roles', 'capabilities', 'sessions'];

    foreach ($tables as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }

        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('users')) {
        DB::table('users')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('users_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('tenants')) {
        DB::table('tenants')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('tenants_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('tenant_memberships')) {
        DB::table('tenant_memberships')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('memberships_status_'.$row->status.'='.$row->count));
    }

    $this->line('catalog_version='.config('identity.catalog_version'));

    return 0;
})->purpose('Report non-sensitive identity and tenancy status.');

Artisan::command('runtime-registry:status', function (): int {
    $tables = [
        'runtime_nodes',
        'runtime_node_endpoints',
        'runtime_node_credentials',
        'runtime_node_capabilities',
    ];

    foreach ($tables as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }

        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('runtime_nodes')) {
        DB::table('runtime_nodes')
            ->select('runtime_family', DB::raw('count(*) as count'))
            ->groupBy('runtime_family')
            ->orderBy('runtime_family')
            ->get()
            ->each(fn (object $row) => $this->line('nodes_family_'.$row->runtime_family.'='.$row->count));

        DB::table('runtime_nodes')
            ->select('desired_state', DB::raw('count(*) as count'))
            ->groupBy('desired_state')
            ->orderBy('desired_state')
            ->get()
            ->each(fn (object $row) => $this->line('nodes_desired_'.$row->desired_state.'='.$row->count));

        DB::table('runtime_nodes')
            ->select('observed_state', DB::raw('count(*) as count'))
            ->groupBy('observed_state')
            ->orderBy('observed_state')
            ->get()
            ->each(fn (object $row) => $this->line('nodes_observed_'.$row->observed_state.'='.$row->count));
    }

    if (Schema::hasTable('runtime_node_endpoints')) {
        DB::table('runtime_node_endpoints')
            ->select('purpose', DB::raw('count(*) as count'))
            ->groupBy('purpose')
            ->orderBy('purpose')
            ->get()
            ->each(fn (object $row) => $this->line('endpoints_purpose_'.$row->purpose.'='.$row->count));
    }

    if (Schema::hasTable('runtime_node_credentials')) {
        DB::table('runtime_node_credentials')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('credentials_status_'.$row->status.'='.$row->count));
    }

    $this->line('catalog_version='.config('runtime_registry.catalog_version'));

    return 0;
})->purpose('Report non-sensitive runtime registry status.');

Artisan::command('runtime-engine:outbox-dispatcher {--once : Process one batch and exit}', function (OutboxDispatcher $dispatcher): int {
    $workerId = gethostname().':outbox:'.getmypid();
    do {
        $dispatcher->dispatchOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the automatic transactional outbox dispatcher.');

Artisan::command('runtime-engine:command-worker {--once : Process one batch and exit}', function (CommandWorker $worker): int {
    $workerId = gethostname().':command:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the generic runtime-operation command worker.');

Artisan::command('runtime-engine:event-normalizer {--once : Process one batch and exit}', function (EventNormalizerWorker $worker): int {
    $workerId = gethostname().':normalizer:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 5));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the generic runtime-event normalizer.');

Artisan::command('runtime-engine:reconciler {--once : Process one batch and exit}', function (ReconciliationWorker $worker): int {
    $workerId = gethostname().':reconciler:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('runtime_engine.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('runtime_engine.poll_seconds', 10));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the generic reconciliation worker.');

Artisan::command('runtime-engine:derive-stale-observations', function (ProjectionService $projection): int {
    $count = $projection->markStale((int) config('runtime_engine.stale_observation_seconds', 300));
    $this->line('stale_observations_marked='.$count);

    return 0;
})->purpose('Derive stale runtime-node observations without manual state authority.');

Artisan::command('runtime-engine:status', function (): int {
    $tables = [
        'runtime_operations',
        'control_plane_outbox_messages',
        'runtime_event_receipts',
        'runtime_observations',
        'runtime_projection_checkpoints',
        'runtime_reconciliation_states',
    ];

    foreach ($tables as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }

        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('runtime_operations')) {
        DB::table('runtime_operations')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('operations_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('control_plane_outbox_messages') && Schema::hasColumn('control_plane_outbox_messages', 'dispatch_status')) {
        DB::table('control_plane_outbox_messages')
            ->select('dispatch_status', DB::raw('count(*) as count'))
            ->groupBy('dispatch_status')
            ->orderBy('dispatch_status')
            ->get()
            ->each(fn (object $row) => $this->line('outbox_dispatch_'.$row->dispatch_status.'='.$row->count));
    }

    if (Schema::hasTable('runtime_event_receipts')) {
        DB::table('runtime_event_receipts')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('event_receipts_status_'.$row->status.'='.$row->count));
    }

    if (Schema::hasTable('runtime_reconciliation_states')) {
        DB::table('runtime_reconciliation_states')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('reconciliation_status_'.$row->status.'='.$row->count));
    }

    $this->line('catalog_version='.config('runtime_engine.catalog_version'));

    return 0;
})->purpose('Report non-sensitive runtime engine status.');

Artisan::command('simulator:ensure-targets', function (ReconciliationRepository $repository): int {
    $count = 0;
    DB::table('runtime_nodes')
        ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
        ->whereIn('desired_state', ['active', 'draining'])
        ->orderBy('id')
        ->get()
        ->each(function (object $node) use ($repository, &$count): void {
            if (DB::table('simulator_profiles')->where('runtime_node_id', $node->id)->exists()) {
                $repository->ensureTarget((string) $node->tenant_id, 'runtime_node', (string) $node->id, (int) $node->configuration_version);
                $count++;
            }
        });
    $this->line('simulator_reconciliation_targets_ensured='.$count);

    return 0;
})->purpose('Automatically ensure reconciliation targets for active deterministic simulator nodes.');

Artisan::command('simulator:event-source {--once : Publish one batch and exit}', function (SimulatorEventSourceWorker $worker): int {
    $workerId = gethostname().':simulator-events:'.getmypid();
    do {
        $worker->workOnce($workerId, (int) config('simulator.batch_size', 10));
        if (! $this->option('once')) {
            sleep((int) config('simulator.poll_seconds', 3));
        }
    } while (! $this->option('once'));

    return 0;
})->purpose('Run the deterministic simulator scheduled-event source.');

Artisan::command('simulator:status', function (): int {
    foreach (['simulator_profiles', 'simulator_states', 'simulator_scheduled_events'] as $table) {
        if (! Schema::hasTable($table)) {
            $this->line($table.'=missing');

            continue;
        }
        $this->line($table.'_count='.DB::table($table)->count());
    }

    if (Schema::hasTable('runtime_nodes')) {
        $this->line('simulator_nodes='.DB::table('runtime_nodes')->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))->count());
        DB::table('runtime_nodes')
            ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
            ->select('desired_state', DB::raw('count(*) as count'))
            ->groupBy('desired_state')
            ->orderBy('desired_state')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_desired_'.$row->desired_state.'='.$row->count));
        DB::table('runtime_nodes')
            ->where('adapter_key', config('simulator.adapter_key', 'simulator-deterministic'))
            ->select('observed_state', DB::raw('count(*) as count'))
            ->groupBy('observed_state')
            ->orderBy('observed_state')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_observed_'.$row->observed_state.'='.$row->count));
    }

    if (Schema::hasTable('simulator_scheduled_events')) {
        DB::table('simulator_scheduled_events')
            ->select('status', DB::raw('count(*) as count'))
            ->groupBy('status')
            ->orderBy('status')
            ->get()
            ->each(fn (object $row) => $this->line('simulator_events_status_'.$row->status.'='.$row->count));
    }
    $this->line('catalog_version='.config('simulator.catalog_version'));

    return 0;
})->purpose('Report non-sensitive deterministic simulator status.');

Schedule::command('runtime-engine:outbox-dispatcher --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:command-worker --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:event-normalizer --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:reconciler --once')->everyMinute()->withoutOverlapping();
Schedule::command('runtime-engine:derive-stale-observations')->everyFiveMinutes()->withoutOverlapping();
Schedule::command('simulator:ensure-targets')->everyMinute()->withoutOverlapping();
Schedule::command('simulator:event-source --once')->everyMinute()->withoutOverlapping();
