[general]
static=yes
writeprotect=no
clearglobalvars=no

[globals]

[from-utcp]
exten => _.,1,NoOp(EXTERNAL_SIP_PEER_INBOUND address=${EXTEN})
 same => n,Answer()
 same => n,Set(EXTERNAL_SIP_PEER_RESULT=answered)
 same => n,Echo()

[to-utcp]
exten => _.,1,NoOp(EXTERNAL_SIP_PEER_OUTBOUND address=${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@utcp-peer,10)
 same => n,Hangup()
