[modules]
autoload = yes
noload = chan_alsa.so
noload = res_hep.so
noload = res_hep_pjsip.so
noload = res_hep_rtcp.so
noload = chan_sip.so
noload = res_stasis.so
noload = app_stasis.so
noload = app_stasis_broadcast.so
noload = res_stasis_answer.so
noload = res_stasis_broadcast.so
noload = res_stasis_device_state.so
noload = res_stasis_playback.so
noload = res_stasis_recording.so
noload = res_stasis_snoop.so
