apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: utcp-traefik
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/component: gateway-api
spec:
  controllerName: traefik.io/gateway-controller
