apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: utcp-application-config
    namespace: utcp-platform
    envs:
      - application-config.properties
secretGenerator:
  - name: utcp-local-data-credentials
    namespace: utcp-platform
    envs:
      - local-data-credentials.properties
  - name: utcp-local-kamailio-db-credentials
    namespace: utcp-platform
    envs:
      - local-kamailio-db-credentials.properties
  - name: utcp-local-reverb-credentials
    namespace: utcp-platform
    envs:
      - local-reverb-credentials.properties
resources:
  - ../../../base/platform
images:
  - name: utcp-api
    newName: utcp-local-registry:5000/utcp/api
    newTag: 0.1.0-k1-dev
  - name: utcp-web
    newName: utcp-local-registry:5000/utcp/web
    newTag: 0.1.0-k1-dev
  - name: utcp-gateway
    newName: utcp-local-registry:5000/utcp/gateway
    newTag: 0.1.0-k1-dev
  - name: utcp-rtpengine
    newName: utcp-local-registry:5000/utcp/rtpengine
    newTag: 0.1.0-k1-dev
  - name: utcp-kamailio
    newName: ghcr.io/kamailio/kamailio
    newTag: 5.8.6-bookworm
