apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/platform
  - ../../base/runtime
  - ../../components/freeswitch-instance
patches:
  - path: asterisk-disabled.yaml
  - path: selected-runtime-service.yaml
images:
  - name: utcp-freeswitch
    newName: utcp-local-registry:5000/utcp/freeswitch
    newTag: 0.1.0-t3-s2c
