apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-from-gateway
  namespace: utcp-platform
  labels:
    app.kubernetes.io/part-of: utcp
    app.kubernetes.io/managed-by: utcp-k3-security
spec:
  podSelector:
    matchLabels:
      utcp.io/network-role: web
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              utcp.io/network-role: gateway
      ports:
        - protocol: TCP
          port: 8080
  egress: []
